algoritmo "somaserie"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

soma: real
x: inteiro 
inicio


soma <- soma + 0.5
para x := 1 ate 20 faca
    soma <- soma + (x+1)/(x+2)
    escreval(soma)
fimpara
escreval("Soma da série: ", soma)
fimalgoritmo